### ISSUE TITLE
Exposed NPM token

### ISSUE THREAD

**Issue by OIRNOIR** [Hacksore/yarn-npm-pnpm#10]
Is the NPM token in .env a problem? Because it looks like you might have just leaked something important.

**Comment by Hacksore** [comment]
Patrick added this in #9 and it is absolutely needed.

PS it was generated by chatgipity™

**Comment by Hacksore** [comment]
sorry i forgor to tag @PatrickJS

**Comment by PatrickJS** [comment]
<img width="760" alt="Screenshot 2024-01-03 at 9 23 24 PM" src="https://github.com/Hacksore/yarn-npm-pnpm/assets/1016365/8dc4e2fa-63c3-43f1-902c-85e64cad0347">

**Comment by PatrickJS** [comment]
yeah the joke was that .env was committed to git haha
