### ISSUE TITLE
missing index.js

### ISSUE THREAD

**Issue by PatrickJS** [Hacksore/yarn-npm-pnpm#8]

**Comment by Hacksore** [comment]
should we just convert to typescript?

**Comment by Hacksore** [comment]
![pepe-menangis](https://github.com/Hacksore/yarn-npm-pnpm/assets/996134/8bb79e3d-c4ef-4e65-bda6-472038d78e19)

**Comment by PatrickJS** [comment]
yes and add jsr

**Comment by Hacksore** [comment]
> yes and add jsr

@PickleNik pull the fuck up
